### ISSUE TITLE
Tabs and toolbar buttons don't display as expected

### ISSUE THREAD

**Issue by chiahsien** [yoyurec/logseq-solarized-extended-theme#10]
**Info:**
- OS: macOS 12.2.1
- Logseq ver: 0.6.9
- Theme ver: 1.8.3
- Do i have the same on default theme? NO

**Description:**
- I don't modify custom css.
- I've tried to apply `default` theme then `logseq-solarized-extended-theme`.
- I've tried to refresh.
- I've tried to restart Logseq.
- Tabs and toolbar buttons don't display as expected.

**Screenshots**
![截圖 2022-05-19 下午10 50 23](https://user-images.githubusercontent.com/1225437/169328219-f6955eff-fd97-474e-9086-2a72a673cefe.png)

**Comment by chiahsien** [comment]
> did you tried uninstall and install theme?

Yes, many times but still the same.

**Comment by yoyurec** [comment]
try new update 1.8.5!

**Comment by chiahsien** [comment]
Tabs change their position, but toolbar buttons still have position issue.
![image](https://user-images.githubusercontent.com/1225437/169645333-4173929b-218e-43b2-9a09-a9567487b26e.png)

**Comment by chiahsien** [comment]
1. Update to 1.8.5
2. Apply default theme then change to this one.
3. Restart Logseq.
4. Here is the UI result.

Any information you need?

![image](https://user-images.githubusercontent.com/1225437/169645788-30d4b3ca-47a5-427b-b924-4e287f8127f9.png)

**Comment by yoyurec** [comment]
looks like JS not applied somehow (
Are there any errors in console?

**Comment by chiahsien** [comment]
I disabled all themes and plugins, left only `Tabs` plugin and `Solarized-extended-theme` enabled. Then I apply the theme and restart Logseq.

Here is an error in console. Let me know if you need any further information or want me to try out something.

<img width="559" alt="image" src="https://user-images.githubusercontent.com/1225437/169691565-44836d4d-c979-4ef6-80c1-5d36c4b845b2.png">

**Comment by yoyurec** [comment]
try new version.... some JS updated

**Comment by chiahsien** [comment]
Updated theme to v1.9.5 and got this result.

<img width="722" alt="image" src="https://user-images.githubusercontent.com/1225437/169700126-00aa7707-2d18-42cc-b4c6-cab3ac84eee9.png">

<img width="559" alt="image" src="https://user-images.githubusercontent.com/1225437/169700106-3872ddaf-4eae-473a-ae44-c2ed59b0e92d.png">

**Comment by yoyurec** [comment]
okayyy... what about 1.9.6? )

**Comment by chiahsien** [comment]
1.9.6 works as expected! 🚀 🥳
