### ISSUE TITLE
Text Size of quoted text

### ISSUE THREAD

**Issue by solariz** [yoyurec/logseq-solarized-extended-theme#12]
**Info:**
- OS: win11
- Logseq ver: 0.6.9
- Theme ver: 1.8.5
- [ ] Do i have the same on default theme? 

**Description:**
Text in Quote blocks is larger compared to normal text.
Is there a setting I can use in custom.css to make this same size as normal text?

**Screenshots**

![screenshot_20220522-105351](https://user-images.githubusercontent.com/4168339/169687633-2b6364ad-3331-4284-a607-071c1c63a844.png)

**Comment by yoyurec** [comment]
my theme didn't chage quotes size. only color...
check default theme plz, sizes also different?

**Comment by solariz** [comment]
ok thanks. figured it out.
