### ISSUE TITLE
It seems some of the components carry over to other themes

### ISSUE THREAD

**Issue by lef-est** [yoyurec/logseq-solarized-extended-theme#13]
For example the tabs area and colorful threads affect other themes, even when this theme is disabled in plugins:
![image](https://user-images.githubusercontent.com/9643637/169871369-47cba5b8-3df6-4c11-b11e-0d635e889994.png)
![image](https://user-images.githubusercontent.com/9643637/169871662-a74aab03-3baf-41cf-915d-3617a46910bd.png) Lines are thinner if solarized is not disabled.
![image](https://user-images.githubusercontent.com/9643637/169871400-84dcbb1f-d267-4b11-9de8-f4b16e907b2d.png) If I disabled, the lines will be thicker but the colors are still there. 

This color scheme can be out of place in other themes, especially the tabs area.

**Comment by yoyurec** [comment]
Theme has JS, so it inject styles into Tabs - disabling is not enough, you need reload Logseq

**Comment by yoyurec** [comment]
Coored lines, it's a plugin? Name?

**Comment by lef-est** [comment]
> Theme has JS, so it inject styles into Tabs - disabling is not enough, you need reload Logseq
Thanks for the clarification!

> Colored lines, it's a plugin? Name?
No, I'm just referring to the colours applied in Solarized Extended (or I thought they are).

**Comment by yoyurec** [comment]
Solarized do not add colors to lines )

**Comment by yoyurec** [comment]
![image](https://user-images.githubusercontent.com/137919/169908019-e18809d2-803c-46dc-95ed-839ae791d01b.png)

**Comment by lef-est** [comment]
Sorry, you're right. It was added by Logtools! (I assumed it's this theme because I noticed this and the tabs around the same time, and those colors really go well with this theme haha)
