### ISSUE TITLE
Provide settings UI

### ISSUE THREAD

**Issue by chiahsien** [yoyurec/logseq-solarized-extended-theme#14]
**Idea**
We can change the settings via `custom.css`, but there are too many options to adjust.
Is it possible to provide a settings UI to customize these options? Maybe it can be integrated into Plugin's setting UI? For example, the [bullet threading](https://github.com/pengx17/logseq-plugin-bullet-threading) plugin is a wrapper for certain CSS settings.

**Comment by yoyurec** [comment]
yes, it's already in roadmap!

**Comment by Gitbreast** [comment]
Expecting. This seems like a highly customizable theme. With a easy way to custom all these features, that will be perfect.

**Comment by yoyurec** [comment]
lot of works done, now on heavy testing stage 💪

**Comment by bioglp** [comment]
terrific work, thank you! However, I would like to restore the home icon, how can I do that?

**Comment by yoyurec** [comment]
@bioglp via CSS variable, but soon it will be in settings!

**Comment by yoyurec** [comment]
@bioglp
i thought one more time (again)...
there is "Journals" menu item
there is `g h` hotkey...
i think i will not add this to options, sorry. to many attention to such small thing.

plz, use custom CSS instead:
```css
:root {
--hidden-home: none;
}
```

**Comment by bioglp** [comment]
> @bioglp via CSS variable, but soon it will be in settings!

@yoyurec in my case, custom CSS is perfect (sidebars are always hidden and hotkey isn't always the fastest way): 5 stars
:root {
--hidden-home: none;
}

**Comment by yoyurec** [comment]
i remember somebody asked me about home... maybe will add )

**Comment by yoyurec** [comment]
DONE!
**⚠️ according to theme init changes - RELOAD REQUIRED! ⚠️** 
https://github.com/yoyurec/logseq-solarized-extended-theme/releases/tag/v2.0.0
