### ISSUE TITLE
remove background and shade

### ISSUE THREAD

**Issue by hodanli** [yoyurec/logseq-solarized-extended-theme#15]
can we get an option to remove background image and shading to get a flat visual. thnx for your effort on this theme.

**Comment by yoyurec** [comment]
But first update to latest v1.10.1

**Comment by hodanli** [comment]
![image](https://user-images.githubusercontent.com/6535865/170282229-2055deac-a63f-49b2-ba09-58c743b2ab55.png)
how can i make the gray area yellow too?

**Comment by yoyurec** [comment]
set any color
    :root {
        --bg-overlay: #d7d1c1;
    }

**Comment by hodanli** [comment]
thnx for the answer. you changed some of the stuff from your readme after my question. sorry i could not follow it religiously.
