### ISSUE TITLE
Nested block layout issue in Document mode

### ISSUE THREAD

**Issue by chiahsien** [yoyurec/logseq-solarized-extended-theme#16]
**Info:**
- OS: macOS
- Logseq ver: 0.7.0
- Theme ver: 1.11.1

**Description:**
When in `Document` mode (toggle with shortcut `t` + `d`), left side of nested block (first level) doesn't look good.

**Screenshots**
<img width="400" alt="截圖 2022-05-26 下午10 18 44" src="https://user-images.githubusercontent.com/1225437/170507323-13f490d8-3172-4ef0-86c6-ffcf9668505a.png">

**Comment by yoyurec** [comment]
Fixed in v1.11.2
