### ISSUE TITLE
Port "Tabs on top" feature back to Tabs plugin

### ISSUE THREAD

**Issue by chiahsien** [yoyurec/logseq-solarized-extended-theme#17]
I asked the Tabs author for **tabs on top** feature and the author [likes this idea too](https://github.com/pengx17/logseq-plugin-tabs/issues/41). Since Solarized Theme implemented this feature already, is it possible to port this feature back to Tabs plugin?

**Comment by yoyurec** [comment]
Of course it's possible )
The question how author will color them? Plugin have no possibility to see Logseq color variables...
