### ISSUE TITLE
Could you please provide small indicators beside the heading text?

### ISSUE THREAD

**Issue by willzhqiang** [yoyurec/logseq-solarized-extended-theme#18]
**Idea**
I tried two themes 
https://github.com/haydenull/logseq-woz-theme
https://github.com/pengx17/logseq-dev-theme
Both of them can display small letters such as h1 h2 close to the Heading1 or Heading2 text.

**Screenshots**
<img width="862" alt="image" src="https://user-images.githubusercontent.com/279170/170918822-31262ad7-ece4-4dc8-a830-0b30e8ce643d.png">
<img width="724" alt="image" src="https://user-images.githubusercontent.com/279170/170918861-d1dcca99-8b13-41bd-a470-ef7162ab6d43.png">

Because we cannot easily tell the difference between h1~h6 only according to the display size, the small letter can help recognize and format heading easily. 

Please consider this feature, it would be nice to provide an option for users to turn if on or off.

**Comment by yoyurec** [comment]
done!
![image](https://user-images.githubusercontent.com/137919/171737668-362b26d9-63b9-4b3a-b42a-9aa8096a0246.png)

https://github.com/yoyurec/logseq-solarized-extended-theme/releases/tag/v1.12.1

**Comment by willzhqiang** [comment]
Great, so fast, will try it later
