### ISSUE TITLE
The theme when enabled messes up the default theme

### ISSUE THREAD

**Issue by nhan000** [yoyurec/logseq-solarized-extended-theme#19]
**Info:**
- OS: Windows
- Logseq ver: win-x64-0.7.1+nightly.20220606
- Theme ver: v1.12.3
- [] Do i have the same on default theme? 

**Description:**
Favicons appeared for external links even when not using it. And spacing between lines are expanded.

**To Reproduce:**

1. Install Solarized extended theme from Marketplace and have it enabled
2. Use Logseq default theme.
3. Reload and check any external link

**Expected behavior:**
Solarized extended theme should be isolated from the default theme.
This also messes up other themes as well such as Dev theme.

**Screenshots**
Solarized Extended Theme disabled
![image](https://user-images.githubusercontent.com/85216095/172198833-4427e2bd-8383-41ce-ab8d-3a42e4d325b2.png)

Solarized Extended Theme enabled
![image](https://user-images.githubusercontent.com/85216095/172199010-53403237-e87b-46d2-a9e9-3b10d4a924c7.png)

**Comment by yoyurec** [comment]
fixed!
https://github.com/yoyurec/logseq-solarized-extended-theme/releases/tag/v1.12.4
