### ISSUE TITLE
FR: Highlight blocks that have sub-blocks

### ISSUE THREAD

**Issue by hkgnp** [yoyurec/logseq-solarized-extended-theme#2]
Great theme! Love it!  

Is it possible to have some visual way to highlight blocks that have child blocks? Currently you only see the arrows when you hover over the blocks.

Thanks in advance!

**Comment by yoyurec** [comment]
Theme version? Screen? tnx!

**Comment by yoyurec** [comment]
Currently in Logseq (and my theme, cose it based on it) you can see "there are childd, man!" via:
* big bullet on collapsed item
* arrow on hover

do you suggest to show arrows always? woudn't it be over complicate design and view?

**Comment by yoyurec** [comment]
do you suggest to show arrows always? woudn't it be over complicate design and view?

why you need more signs of child if you see identation and content already? hm... can you explain the reason and idea?

**Comment by yoyurec** [comment]
like this?
![image](https://user-images.githubusercontent.com/137919/168093644-38463893-3c46-45c9-b902-6877429fbc9b.png)

**Comment by hkgnp** [comment]
Apologies for the late reply! And sorry if I was not more specific.
Basically in queries, there are no bullets, so you cannot tell if a
particular query item has a dropdown list or not.
For example, out of the 4 queries below, the 2nd one actually has
sub-bullets. But you can't tell until you hover your mouse over the left
hand area.
This only applies to query results.
For regular blocks, it is fine.
[image: Screenshot 2022-05-12 at 10.53.45 PM.png]

**Comment by yoyurec** [comment]
your sceenshot lost ((

**Comment by hkgnp** [comment]
> your sceenshot lost ((

Sorry! Hope it shows now!
<img width="97" alt="Screenshot 2022-05-12 at 11 00 45 PM" src="https://user-images.githubusercontent.com/47936793/168106064-2d964484-3e7f-48b9-a736-013649fa7b99.png">

**Comment by yoyurec** [comment]
can you provid markdown with todos and query? i need to see generated html/css to play with...

**Comment by yoyurec** [comment]
1. After you click on arrow - do child expands? mine not (( so see no reason of this feature. can you provide your md code with items and query?
2. comparing to other blocks - they have attribute `hasChild`, so arrows can be styled to show always, cut in current case - logseq think that there is no childs - `hasChilds="false"`!
![image](https://user-images.githubusercontent.com/137919/168110072-d31855cd-8a18-4ce7-8b9d-412dd5445107.png)
3. we can tell to show always - but then it will be a mess ((
![image](https://user-images.githubusercontent.com/137919/168110900-f1d820e1-4e96-4459-a651-533bafea8773.png)

Looks like it's a LS bug it attribute, but if after opening it doesn't shows sub-content - then it;''s not a bug )
At least with my trying to reproduce your case...

**Comment by hkgnp** [comment]
> 1. After you click on arrow - do child expands? mine not (( so see no reason of this feature. can you provide your md code with items and query?
> 2. comparing to other blocks - they have attribute `hasChild`, so arrows can be styled to show always, but in current case - logseq think that there is no childs - `hasChilds="false"`!
>    ![image](https://user-images.githubusercontent.com/137919/168110072-d31855cd-8a18-4ce7-8b9d-412dd5445107.png)
> 3. we can try to show always - but then it will be a mess ((
>    ![image](https://user-images.githubusercontent.com/137919/168110900-f1d820e1-4e96-4459-a651-533bafea8773.png)
> 
> Looks like it's a LS bug it attribute, but if after opening it doesn't shows sub-content - then it''s not a bug ) At least with my trying to reproduce your case...

Thanks for sharing! It's ok, small thing. Still love your theme!

**Comment by yoyurec** [comment]
> After you click on arrow - do child expands? 
do? )

**Comment by hkgnp** [comment]
> > 1. After you click on arrow - do child expands?
> 
> do? )

Yup it does!

**Comment by yoyurec** [comment]
hm... and `hasChilds="true"!`?
can you send me test .md files so i can reproduce? i need to test. maybe your FR possible...

**Comment by hkgnp** [comment]
Yes, the `hasChild="true"`.
It's basically a query, so I am not sure how to send you the `.md` file.

**Comment by yoyurec** [comment]
post here as code. items + query
