### ISSUE TITLE
[bug] Block References headers size

### ISSUE THREAD

**Issue by debanjandhar12** [yoyurec/logseq-solarized-extended-theme#20]
**Info:**
- OS: Win 11
- Logseq ver: 0.7.3
- Theme ver: 1.12.4

**Bug Description:**
Block References containing headers retain their size. 
![image](https://user-images.githubusercontent.com/49021233/172869794-c39dd5ed-68da-4ef7-8c7a-b815208257c2.png)

**Expected behavior:**
The bellow image shows how block reference containing headers are handed in default theme. The same behavior is there in Dev Theme as well.
 ![image](https://user-images.githubusercontent.com/49021233/172869325-7aa2526e-282a-459c-a97b-76272bca5828.png)

NB: Thanks for the theme! Love this ❤️

**Comment by yoyurec** [comment]
So you want to hide `h3` label?
BTW, Dev theme have it 
![image](https://user-images.githubusercontent.com/137919/173253450-ff0b7e23-6bfb-47e3-b1b9-1f2c75438e54.png)

**Comment by debanjandhar12** [comment]
> So you want to hide `h3` label?
> BTW, Dev theme have it

No. I want all the header levels when used as block reference to be of the same size as the other text. Talking in terms of css:
```css
.block-ref :is(h1, h2, h3, h4, h5, h6) {
  border-bottom: none;
  font-size: 1rem;
}
```
Source: https://github.com/logseq/logseq/blob/81904156f864a2416b8c5f8825b3d7885cea1539/src/main/frontend/components/block.css#L411

**Comment by yoyurec** [comment]
https://github.com/yoyurec/logseq-solarized-extended-theme/releases/tag/v1.12.5
fixed
