### ISSUE TITLE
The background setting will revert to the default one after toggle between light and dark mode

### ISSUE THREAD

**Issue by z1ggy-o** [yoyurec/logseq-solarized-extended-theme#22]
**Info:**
- OS: macOS 12.4
- Logseq ver: 0.7.3
- Theme ver: 1.12.4
- [ ] Do I have the same on the default theme?  Sorry, I don't know.

**Description:**

I tried to use the given setting in the documentation to disable the background image and it works.
However, after I toggle between light and dark mode a few times, the background image returns again.

**To Reproduce:**
 Toggle between light mode and dark mode twice. 

For example, we are in the light mode right now and use `t t` to dark mode. When using `t t` to back to light mode, the setting reverts to the background setting.

After I tried a few times, if we are in the light mode, even toggle once can reproduce the problem.

**Expected behavior:**
The modified setting should remain.

**Screenshots**
<img width="742" alt="image" src="https://user-images.githubusercontent.com/19348185/173263321-dfe431a2-9c16-40b8-ba27-9b1118c53cea.png">
This is my settings.

![iShot_2022-06-13_09 38 11](https://user-images.githubusercontent.com/19348185/173264658-225f1d12-b2c6-4095-877f-46f92ed2a820.gif)
Here, I keep using `t t` to switch between light and dark mode.

**Comment by yoyurec** [comment]
looks like Logseq team changed `custom.css` behaviour and priority.
just add `!important` after colors.

readme updated

**Comment by z1ggy-o** [comment]
It works now. Thank you for your brilliant job and quick reply!
