### ISSUE TITLE
External links to the specific site icon is how to achieve

### ISSUE THREAD

**Issue by YangWaldon** [yoyurec/logseq-solarized-extended-theme#25]
I have asked you for help explaining how the site icon for external links is implemented, and I would like to add it to my custom. css
![image](https://user-images.githubusercontent.com/49675185/177068914-7026bb3d-d5fd-42c3-a957-733bfa810881.png)

**Comment by yoyurec** [comment]
previously the were done via CSS - https://github.com/yoyurec/logseq-solarized-extended-theme/blob/e1565b05f5eabacedb977b587273bee38da05416/src/custom.css#L404-L470
but it's only for ~20 top sites, and list populated manually ((

not i'm using JS version with content editor detections, google favicons API and CSS variables...

**Comment by YangWaldon** [comment]
Thank you! 
① So, if you want to display all the site icons, it is not feasible to use custom.css only, right? 
② Also I have another question, why the code related to Search panel in the theme.css file of the plugin does not work after I copy and paste it into custom.css, Is this functionality also not possible through a pure css solution?

**Comment by yoyurec** [comment]
1) right. only JS ((
2) it's also done via JS - to rearrange toolbar elements. Their default order too hard and too buggy for CSS job

**Comment by YangWaldon** [comment]
Okay, thanks for the answer！
