### ISSUE TITLE
Banner position is wired

### ISSUE THREAD

**Issue by TankCool** [yoyurec/logseq-solarized-extended-theme#26]
**Info:**
- OS: Mac OS
- Logseq ver: 0.7.6
- Theme ver: v1.14.1
- [ ] Do i have the same on default theme? no

**Description:**
When the left sidebar and right sidebar are hiden and  use `t w` switch wide mode, the banner position will shift left.

**Screenshots**

![Screen Shot 2022-07-06 at 11 58 45](https://user-images.githubusercontent.com/5235399/177465669-33439c0f-80c5-4150-9aab-869baa8fd337.png)

**Comment by TankCool** [comment]
v1.6.0
  
​
  
​This only happens on big screen.

**Comment by yoyurec** [comment]
check updated theme 1.14.2 + updated banner plugin v1.6.1

**Comment by TankCool** [comment]
🥳It works, thank you so much!
