### ISSUE TITLE
Banner position is something wrong

### ISSUE THREAD

**Issue by Horinne** [yoyurec/logseq-solarized-extended-theme#27]
**Info:**
- OS: 
- Logseq ver:0.7.6
- Theme ver: 1.14.2
- [ ] Do i have the same on default theme? 

**Description:**
There's a gap between banner picture and block.

**To Reproduce:**
 ...

**Expected behavior:**
 ...

**Screenshots**
<img width="1080" alt="image" src="https://user-images.githubusercontent.com/90925406/178286400-03bc1265-25d4-472e-b2e6-6704317f63cf.png">

**Attach files**
Add (via drag-n-drop) .zip with `.md` files (if it needs) to help with bugfixind

**Comment by yoyurec** [comment]
it does not default theme settings - try to disable your customizations and write results.

**Comment by Horinne** [comment]
I tried, but still not work.

**Comment by yoyurec** [comment]
can you use devTools to inspect this element with "gap"?
`Ctrl+Shift+i" -> "Elements" and target banner (or nex element after) to find marign/padding...
https://www.loom.com/share/a78d98c73c834574acd1608e9c523b6c

and record loom video

**Comment by Horinne** [comment]
Hope it works
https://www.loom.com/share/ad7269ae59b7410695d882158d2806b2

**Comment by yoyurec** [comment]
Ohhhh! You should mention "on child block page" )

**Comment by yoyurec** [comment]
working on fix...

**Comment by yoyurec** [comment]
fixed in 1.14.3!
