### ISSUE TITLE
There‘s a weird gap again

### ISSUE THREAD

**Issue by Horinne** [yoyurec/logseq-solarized-extended-theme#28]
**Info:**
- OS: macOS
- Logseq ver:0.7.7
- Theme ver: 1.14.4
- [ ] Do i have the same on default theme? 

**Description:**
There's a gap between PDF and notes whenever you open a PDF file.

**To Reproduce:**
 ...

**Expected behavior:**
 ...

**Screenshots**
<img width="1052" alt="image" src="https://user-images.githubusercontent.com/90925406/180036549-37dbb71c-3e6b-4a0a-9b6f-b321b8139f0d.png">

**Attach files**
Add (via drag-n-drop) .zip with `.md` files (if it needs) to help with bugfixind

**Comment by yoyurec** [comment]
fixed in latest release
