### ISSUE TITLE
Search bar is not centered

### ISSUE THREAD

**Issue by TITC** [yoyurec/logseq-solarized-extended-theme#29]
**Info:**
- OS: windows11
- Logseq ver:0.7.6
- Theme ver: 1.14.4
- [ ] Do i have the same on default theme? 

**Description:**
A clear and concise description of what the bug is......
call logseq default search function, the search bar is biased to left but not center.
![image](https://user-images.githubusercontent.com/35098797/180321070-8bc36bc7-735f-43ca-9c99-c2aa07dd43ac.png)

**To Reproduce:**
just call logseq default search function

**Expected behavior:**
In the Logseq default light theme, the search bar can be centered.
![image](https://user-images.githubusercontent.com/35098797/180320993-5d024da9-c719-4d15-a82c-634a6be4f968.png)

**Screenshots**

**Attach files**
Add (via drag-n-drop) .zip with `.md` files (if it needs) to help with bugfixind

**Comment by yoyurec** [comment]
it's not a bug, it's a feature.... whole UI reworked
Search popup appears right near search field (like in browser)

**Comment by yoyurec** [comment]
https://github.com/yoyurec/logseq-solarized-extended-theme#-search-panel
