### ISSUE TITLE
no rounded corners on certain menus

### ISSUE THREAD

**Issue by lef-est** [yoyurec/logseq-solarized-extended-theme#3]
Thanks for this amazing theme!
The Plugins menu and Themes menu have no rounded corners on right side, not sure if it's by design though.
![image](https://user-images.githubusercontent.com/9643637/168258145-5cb56428-d330-4459-ab52-838e957e6c65.png)

**Comment by yoyurec** [comment]
yes, popups styles was heavy reworked for Search panel, so Plugins page affected a little ))
waiting for updating plugin on market - then it will be autofixed or i'll check your issue again...

**Comment by yoyurec** [comment]
theme verion?

**Comment by yoyurec** [comment]
uninstal, then install plugin
in latest versions it's fixed!
