### ISSUE TITLE
please add find in page like cmd + f

### ISSUE THREAD

**Issue by l3456** [yoyurec/logseq-solarized-extended-theme#30]
**Idea**
Please add find in page like cmd + f on browser tabs. Thanks for awesome theme : )

**Comment by yoyurec** [comment]
try update Logseq default hotkey settings
![image](https://user-images.githubusercontent.com/137919/180507224-6bdca617-045e-4009-b475-4bd14d102e61.png)

**Comment by yoyurec** [comment]
or try "Vim shortcuts" plugin
https://discord.com/channels/725182569297215569/900642753162137610/998329409612296222
![image](https://user-images.githubusercontent.com/137919/180509467-e4d52de3-b4fd-45b8-9a8f-700a6895f096.png)
