### ISSUE TITLE
Can the link pasting also capture page title, it already shows icon

### ISSUE THREAD

**Issue by l3456** [yoyurec/logseq-solarized-extended-theme#31]
**Idea**
When we paste a link - this plugin identifies the website and show appropriate icon, I feel it can be useful if it also captures the title of the page as the name of the link.
Basically this: https://github.com/0x7b1/logseq-plugin-automatic-url-title/ but instead of installing another new plugin maybe this feature can be added in this plugin itself ?

**Screenshots**
Add some pictures to get the idea if needed

**Attach files**
Add (via drag-n-drop) .zip with `.md` files if it help me with experiments

**Comment by yoyurec** [comment]
not planned ((
try to use (as i do) Chrome browser plugin
https://chrome.google.com/webstore/detail/rich-url/bkjdcppkdgccnhjibfhlhmeiafnjfamk

**Comment by l3456** [comment]
@yoyurec, Thanks for sharing the chrome plugin.
