### ISSUE TITLE
Graph switch dropdown in left sidebar is hidden 

### ISSUE THREAD

**Issue by debanjandhar12** [yoyurec/logseq-solarized-extended-theme#33]
**Info:**
- OS: Win 11
- Logseq ver: Latest
- Theme ver: Latest

**Description:**
Default Theme:
![image](https://user-images.githubusercontent.com/49021233/182604711-b9fd508d-3a5e-45ba-9014-ffa921212fb0.png)
Solarized Theme:
![image](https://user-images.githubusercontent.com/49021233/182604771-961c625a-de69-4aea-8b3f-b0de14b8667e.png)

**Comment by yoyurec** [comment]
working on fix...

**Comment by yoyurec** [comment]
fixed in **v1.18.3**
