### ISSUE TITLE
Missing menu items

### ISSUE THREAD

**Issue by gammonmark** [yoyurec/logseq-solarized-extended-theme#34]
**Info:**
- OS: Mac OS 12.5
- Logseq ver: 0.7.9
- Theme ver: 1.18.0

**Description:**
- The left menu loses (it is sometimes there at the startup of Logseq, then disappears) the "Journals" item. 
- The top menu (where search bar ends) loses the plugin icons on pages other than "Home". Returning home brings the icons back, but they disappear on all other pages

**Expected behavior:**
 These items remain in their respective menus, unless this is a theme feature? If so, can it be controlled in css settings?

**Screenshots**
![CleanShot 2022-08-05 at 09 49 37](https://user-images.githubusercontent.com/5113951/183115542-3b837b3c-197a-400d-b8e0-288baf0faa7a.png)

![CleanShot 2022-08-05 at 09 49 04](https://user-images.githubusercontent.com/5113951/183115572-6f0e598b-3bd0-4b00-a45e-93186ff18b51.png)

![CleanShot 2022-08-05 at 10 02 03](https://user-images.githubusercontent.com/5113951/183116418-8c8e0f8d-9410-4d76-8ccb-2f41a479d6b6.png)

**Comment by yoyurec** [comment]
working on fix...

**Comment by yoyurec** [comment]
fixed in **v1.18.3**

**Comment by gammonmark** [comment]
Hi Yuriy, thanks for updates. The v1.18.4 fixes the Journals item for me, but not the plugin icons. They still disappear once I navigate away from home.
![CleanShot 2022-08-08 at 08 08 56](https://user-images.githubusercontent.com/5113951/183438093-522eaccc-d80d-4b36-90ab-12933d2a8ccb.png)

**Comment by yoyurec** [comment]
can you do devTools inspect siblings of dots menu button? (Cmd+Shift+i)

**Comment by gammonmark** [comment]
From what I can tell, I don't see the buttons HTML at dots menu button. Let me know if helpful to screenshot that. I may also try to just uninstall and reinstall the theme and see if that helps, if others are not experiencing this issue.

**Comment by gammonmark** [comment]
No luck with reinstall. Also, just to confirm, the plugin buttons are showing on the "Home" page, but as soon as I navigate to any other page, I get only the 3 dot button.

**Comment by gammonmark** [comment]
@yoyurec I discovered some code in my custom css file that was the culprit with the plugin buttons. Sorry I didn't think to review that before. This resolved it for me, I'll close this issue. Thanks for the follow up!
