### ISSUE TITLE
Fetch link favicons even when feature disabled

### ISSUE THREAD

**Issue by constfold** [yoyurec/logseq-solarized-extended-theme#35]
**Info:**
- OS: Windows 11
- Logseq ver: 0.7.9
- Theme ver: 1.18.0
- [ ] Do i have the same on default theme? 

**Description:**
I disabled the "Auto favicons for external links" by using `--favicons: none;` as there is no network in my work place. But then found there still are request about favicon.

**To Reproduce:**
 Disable that feature, input some links, then you would see the network requests.

**Expected behavior:**
 Not fetch favicon when auto favicon disabled at all.

**Screenshots**
![Snipaste_2022-08-07_16-35-56](https://user-images.githubusercontent.com/65550294/183282803-c0cd431b-6c90-43a3-9f10-961e370052fb.jpg)

**Attach files**

**Comment by yoyurec** [comment]
it was "CSS only" solution for disable. now working on JS with configuration via Logseq plugins settings

**Comment by constfold** [comment]
gotcha. Thanks for your hard work, this is the best logseq theme I ever use

**Comment by yoyurec** [comment]
DONE!
**⚠️ according to theme init changes - RELOAD REQUIRED! ⚠️** 
https://github.com/yoyurec/logseq-solarized-extended-theme/releases/tag/v2.0.0
