### ISSUE TITLE
Is it possible to plug in some of the features in a theme so that they can be used with other themes

### ISSUE THREAD

**Issue by YangWaldon** [yoyurec/logseq-solarized-extended-theme#36]
Because logseq currently has so many themes and each has its own pros and cons, but logseq-solarized-extended-theme is really the best theme I've seen so far. Sometimes I also find that the self-contained theme works well, but when using the default theme, I really want some of the features in the logseq-solarized-extended-theme theme, such as the following
![image](https://user-images.githubusercontent.com/49675185/184476754-2f39304d-5ebe-4616-bc6e-b6b69a501736.png)
So would the developers consider the possibility of making a separate plugin for these features in that theme, so that it can be used in combination with other themes, which would surely be very popular

**Comment by yoyurec** [comment]
Extracting features to separate plugin good idea..
BUT some of features (for ex. favicons) too complicated and too connected to theme CSS/JS...
Also hard to know other themers UI elements, they styled in different way - i can't cover reseting all their icons and adding my own.

In few days will be release with settings, in a week settings v2 with colors editing - so theme will be not just Solarized ))

About reusing - some theme & plugin devs already insriped by SolExt + i do pull requests to their repos to improve ))

**Comment by yoyurec** [comment]
@YangWaldon
what cons you see in my theme?
what pros you see in other themes, missed in my?

**Comment by YangWaldon** [comment]
I think your theme is the best. At the moment it seems that I would like to be able to use the features you developed in your theme with links automatically adding page icons, resetting toolbars and search boxes and query styles under the default theme of logseq, I don't know if this will be possible in the future

**Comment by yoyurec** [comment]
>  under the default theme of logseq

like default font, white color, ...
what else? i need a list of most important thing from default theme to not undo every CSS line of SolExt ))

**Comment by YangWaldon** [comment]
Just add some solarized theme features to the default theme, other things like homepage width, color, font, size, etc. don't need to be changed.
