### ISSUE TITLE
Export background is not friendly

### ISSUE THREAD

**Issue by lion-no-back** [yoyurec/logseq-solarized-extended-theme#37]
I use the Doc View Exporter plugin to export the page, and then offline to html, and it works well before your theme update, which can make the exported page consistent with the page displayed on logseq, but now it doesn't work, it's very unfriendly , I compressed and packaged the file, you can take a look, I hope to return to the previous effect, I really like the two plug-ins you developed, they are very good
[compare.zip](https://github.com/yoyurec/logseq-solarized-extended-theme/files/9347566/compare.zip)

**Comment by yoyurec** [comment]
Lucky me & you - new upcoming version will be 95% autofixed )
Just need to add few CSS lines for layout... after "Doc View Exporter" dev will approve my PR

**Comment by yoyurec** [comment]
DONE!
**⚠️ according to theme init changes - RELOAD REQUIRED! ⚠️** 
https://github.com/yoyurec/logseq-solarized-extended-theme/releases/tag/v2.0.0
