### ISSUE TITLE
The search box is incomplete

### ISSUE THREAD

**Issue by YangWaldon** [yoyurec/logseq-solarized-extended-theme#38]
As you can see below, there is a section of the search box that doesn't drop down and looks cut off
![image](https://user-images.githubusercontent.com/49675185/184817244-36744ac6-b7dd-4b3d-8d83-d5d7cd0e98d7.png)

**Comment by yoyurec** [comment]
it's 2 separated elements - search "button" and search popup. according to different amount of plugins it's width CSS fixed to some "median" value. so it's not cutted, but just not responsive.

in next versions will try to set both width equal.

**Comment by YangWaldon** [comment]
Ok, equal width would look better, please tell me when the next version will be released

**Comment by yoyurec** [comment]
few days )

**Comment by yoyurec** [comment]
Fixed!
**⚠️ according to theme init changes - RELOAD REQUIRED! ⚠️** 
https://github.com/yoyurec/logseq-solarized-extended-theme/releases/tag/v2.0.0

**Comment by YangWaldon** [comment]
Just updated the theme plugin, have a few questions 
① The width of the right sidebar can not be manually adjusted, as shown below
![image](https://user-images.githubusercontent.com/49675185/185026481-2ede02a9-5892-4aa9-b26a-2f826b8c1d98.png)
② Is it no longer possible to modify the background color in custom.css, I hope to add the option to modify the color as soon as possible

**Comment by yoyurec** [comment]
1. are u sure?
![image](https://user-images.githubusercontent.com/137919/185111076-8a6ed69f-30dd-405a-b301-5b2e32995ad7.png)

2. yes, colors options will be added in few days

**Comment by YangWaldon** [comment]
> are u sure?

I'm pretty sure that when I set both widths in Settings > Plugin Settings > solarized plugin settings, after the maximum width is set to a larger one, say 2000 or 1800, the right hand side bar won't open because the main page width doesn't automatically narrow, which is equivalent to squeezing the right hand side bar out

**Comment by yoyurec** [comment]
theme just overwrites DEFAULT logseq variables

can you say app width and theme width settings to reproduce? maybe it can be fixed somehow, but as i said - no Logseq logic was touched.

**Comment by YangWaldon** [comment]
① 我在试用了一天的默认主题之后，刚才切换回solarized主题，发现侧边栏的宽度又可以调整了······
② 还发现一个问题，就是刚切换到solarized主题的时候，打开右侧栏的图标是没有出现的，当我用快捷键打开右侧栏之后，它才能出现

**Comment by YangWaldon** [comment]
One more issue to report, the bold style is not working. Just to clarify, I added the following code to custom.css to change the bold style, which works fine in other themes, but not in the solarized theme
![image](https://user-images.githubusercontent.com/49675185/185272302-98b08927-5798-46ac-9dcc-cbb122aba7d6.png)
↓
![image](https://user-images.githubusercontent.com/49675185/185272323-aca1ed58-073c-4d8b-ad27-06a78cd81028.png)

![image](https://user-images.githubusercontent.com/49675185/185272333-c4665ebb-cc84-4369-9e82-8dd2d017141a.png)

**Comment by yoyurec** [comment]
i think you can use different issues for different bugs )

**Comment by yoyurec** [comment]
> ③ Will you be able to adjust the background color of the main page, the left column and the right column after the color adjustment option is introduced in the future? I like the background color of the default theme very much

the will be:
* **content bg** (main content +right sidebar content clocks) color
*  and **UI bg** (head+sidebars+tabs)
![image](https://user-images.githubusercontent.com/137919/185518291-54cb9c6e-9aad-4e9f-b703-24f4f147d6b0.png)

**Comment by yoyurec** [comment]
> One more issue to report, the bold style is not working. Just to clarify, I added the following code to custom.css to change the bold style, which works fine in other themes, but not in the solarized theme ![image](https://user-images.githubusercontent.com/49675185/185272302-98b08927-5798-46ac-9dcc-cbb122aba7d6.png) ↓ ![image](https://user-images.githubusercontent.com/49675185/185272323-aca1ed58-073c-4d8b-ad27-06a78cd81028.png)
> 
> ![image](https://user-images.githubusercontent.com/49675185/185272333-c4665ebb-cc84-4369-9e82-8dd2d017141a.png)

there is bold, but thin )) 500 instead of default 700 (text with 700 looks blurry)

BTW, are you using custom font in Logseq?
this one
![image](https://user-images.githubusercontent.com/137919/185518690-ee907e80-f4c1-42c8-9326-a23ee0e12a4a.png)

and this one (windows custom font?)
![image](https://user-images.githubusercontent.com/137919/185518720-008fea20-96ae-4940-af91-f93dc529bd98.png)

**Comment by YangWaldon** [comment]
> > ③ Will you be able to adjust the background color of the main page, the left column and the right column after the color adjustment option is introduced in the future? I like the background color of the default theme very much
> 
> there will be:
> 
> * **content bg** (main content +right sidebar content clocks) color
> * and **UI bg** (head+sidebars+tabs)
>   ![image](https://user-images.githubusercontent.com/137919/185518291-54cb9c6e-9aad-4e9f-b703-24f4f147d6b0.png)

In other words, in the image below, the color of the area where the arrow is pointing can be changed, right?
![image](https://user-images.githubusercontent.com/49675185/185519965-ad399264-b70c-4ec2-8fc3-712dbf0ca645.png)

**Comment by YangWaldon** [comment]
> BTW, are you using custom font in Logseq?

Yes, I'm using a custom font in custom.css
![image](https://user-images.githubusercontent.com/49675185/185520218-e74c5fa6-121a-449f-934f-e235dba57a63.png)

**Comment by yoyurec** [comment]
> In other words, in the image below, the color of the area where the arrow is pointing can be changed, right?

yes )
![image](https://user-images.githubusercontent.com/137919/185532374-229ac1de-e9f9-4269-86ac-bfa51ed38295.png)

**Comment by yoyurec** [comment]
> > BTW, are you using custom font in Logseq?
> 
> Yes, I'm using a custom font in custom.css ![image](https://user-images.githubusercontent.com/49675185/185520218-e74c5fa6-121a-449f-934f-e235dba57a63.png)

then you before submitting bug it will be good to check is it appears with "untouched" SolExt. i can't support your customizations ))

**Comment by yoyurec** [comment]
> > In other words, in the image below, the color of the area where the arrow is pointing can be changed, right?
> 
> yes ) ![image](https://user-images.githubusercontent.com/137919/185532374-229ac1de-e9f9-4269-86ac-bfa51ed38295.png)

+ few autogenareted shaedes for borders, deep block levels, alt text color, etc... 😎

**Comment by YangWaldon** [comment]
> then before you submit the bug it will be good to check is it appears with "untouched" SolExt. i can't support your customizations )) 

So the reason the bold style is not working is because I'm using a custom font? And this bug is not fixable, right?

**Comment by yoyurec** [comment]
bold was maked thinner and with FiraSans font looked better (in your font bold-notbold diff almost minor). will revert on next release...
