### ISSUE TITLE
Background image setting is invalid

### ISSUE THREAD

**Issue by lion-no-back** [yoyurec/logseq-solarized-extended-theme#4]
I really like the theme you made. Through readme, I learned that this theme is what I have been looking for, especially the background image customization, so I set it myself through your description, and found that it seems to have no effect, not sure if it's not that I'm doing something wrong, or...

https://user-images.githubusercontent.com/100990301/168406440-4b4b3e20-010f-438a-9ef9-3c70a2441f81.mp4

**Comment by lion-no-back** [comment]
The problem has solved.I opened custom.css in the package directory of the plugin, then configured it in it, then restarted logseq, it was successful, thank you

**Comment by yoyurec** [comment]
I think css somehow heavy cached...
Try:
1) edit custom css with external editor, not in LS!
2) sonetemes it updates immediately, but for sure - do "Refresh"  (not Reindx!) graph

BTW, not about issue... but open unsplash image detail page and only then copy to have big image, not 500px wide.

**Comment by yoyurec** [comment]
> I opened custom.css in the package directory of the plugin

it will be deleted on next update! do not do this )
use yor own! `graph-name/logseq/custom.css`
