### ISSUE TITLE
How to disable "grid"?

### ISSUE THREAD

**Issue by zerone01y** [yoyurec/logseq-solarized-extended-theme#41]
When I use a tag named "grid" (e.g. powergrids) but I don't want to use the grid-style look. "Grid" is a very common word and maybe

Is there any way for me to overwrite the styles? Thank you for your help!

**Comment by yoyurec** [comment]
you are right, in next release i will change utility tag for something else, like ".grid"

**Comment by yoyurec** [comment]
check latest version!
