### ISSUE TITLE
block-bullet-border-color in dark mode issue

### ISSUE THREAD

**Issue by dale502** [yoyurec/logseq-solarized-extended-theme#42]
block-bullet-border-color in dark mode hard to see

<img width="144" alt="image" src="https://user-images.githubusercontent.com/69394230/186792641-e9a759ef-b8bd-4a64-a50f-b568199ae53a.png">

**Info:**
- OS: macos
- Logseq ver: 0.8.2
- Theme ver: 2.0.3

**Comment by yoyurec** [comment]
bullets will be more visible in next release. today/tomorrow

**Comment by dale502** [comment]
i get it
change the guideline into this will fix it
--ls-guideline-color: var(--solext-accent-lighter);

**Comment by yoyurec** [comment]
but guideline is not bullets, mentioned by you....

**Comment by yoyurec** [comment]
check latest version!
