### ISSUE TITLE
right click a bullet  dot no pop up menu 

### ISSUE THREAD

**Issue by dale502** [yoyurec/logseq-solarized-extended-theme#43]
- OS: macos
- Logseq ver: 0.8.2
- Theme ver: 2.1.2

**Comment by TrismegistusS** [comment]
Same here.

**Comment by yoyurec** [comment]
interesting why Mac differs from PC. on Pc works good. will try to fix, but have no mac ((((((

**Comment by dale502** [comment]
i find it, turn on the tabs pulgin, pop up menu works
 otherwise, pop up menu not works

**Comment by yoyurec** [comment]
tnx, will check...
meanwhile installing MacOS to VirtualBox ))

**Comment by YangWaldon** [comment]
> i find it, turn on the tabs pulgin, pop up menu works otherwise, pop up menu not works

① If you turn off the tabs plugin, the Agenda plugin will not work, turn on the tabs plugin to open the Agenda plugin page properly
![image](https://user-images.githubusercontent.com/49675185/187461506-3717aa50-bc1c-4afe-bf68-51a751e68f18.png)
![image](https://user-images.githubusercontent.com/49675185/187461597-3d8c5b2b-305a-44bc-92ac-caa95d02b70f.png)

② The top and bottom navigation buttons of the TOC Generator plugin will not work if the solarized theme is used, regardless of whether the tabs plugin is enabled or not.
![image](https://user-images.githubusercontent.com/49675185/187461823-81fbbf0a-ea87-4ee2-9a41-af546a6bcc72.png)
![image](https://user-images.githubusercontent.com/49675185/187461855-7a046192-e79e-4269-8e84-690f7ee4336a.png)
![image](https://user-images.githubusercontent.com/49675185/187462086-c6d0592f-1771-4863-8af9-78aebefc3505.png)

**Comment by yoyurec** [comment]
@YangWaldon issue moved to new one #44

**Comment by yoyurec** [comment]
> i find it, turn on the tabs pulgin, pop up menu works otherwise, pop up menu not works

fix found! will release today

**Comment by yoyurec** [comment]
check latest v2.1.3

**Comment by TrismegistusS** [comment]
works perfectly, tanks a lot!
