### ISSUE TITLE
solarized+tabs  ⇢  Text Wrapper failure

### ISSUE THREAD

**Issue by YangWaldon** [yoyurec/logseq-solarized-extended-theme#45]
**Info:** - OS: window10 - Logseq ver: 20220830nightly - Theme ver: i have issue on SolExt theme with my `custom.css`?

**Description:** 
① The Text Wrapper plugin does not work when using the solarized plugin theme and the tabs plugin is enabled. Specifically, when the text is selected, the Text Wrapper plugin's hover action bar will cover the text, which will affect the experience. As shown below
![image](https://user-images.githubusercontent.com/49675185/187597651-baa3c18a-6c71-4c41-978f-c13da272f90c.png)

② But also using the solarized plugin theme, when I turn off the tabs plugin, Text Wrapper plug-in use will not have any problems, will not happen to block the selected text, as shown below
![image](https://user-images.githubusercontent.com/49675185/187597707-e50e17d0-425b-4c50-a91e-fbcf7718b8f2.png)

③ If the theme is not using the solarized plugin, turning on the tabs plugin will not affect the use of the Text Wrapper plugin either
![image](https://user-images.githubusercontent.com/49675185/187597839-77960e43-496c-4be7-89ff-f712b810abd4.png)

**Screenshots**

**Comment by yoyurec** [comment]
check v2.1.5

**Comment by YangWaldon** [comment]
still failure

**Comment by yoyurec** [comment]
update to latest, maybe reload LS (Ctrl+R)
just checked again (maybe LS 0.8.3 broke something, but not) - it works...

**Comment by YangWaldon** [comment]
update , it is okey
