### ISSUE TITLE
WAITING has very low contrast in references section

### ISSUE THREAD

**Issue by memeplex** [yoyurec/logseq-solarized-extended-theme#48]
**Info:**
- OS: macOS Monterey
- Logseq ver: 0.8.5
- Theme ver: 2.1.6
- [x] ⚠ Do i have issue on SolExt theme with DISABLED my `custom.css`? Yes
- [x] ⚠ Do i have the same on default theme? No

**Description:**

In linked/unliked references section (and, in general, other search results) the background is darker and the WAITING marker is hardly visible because of low contrast. This also happens with the Logseq_original preset.

**Screenshots**

<img width="108" alt="image" src="https://user-images.githubusercontent.com/2845433/189015653-1a80b205-ed76-43cf-9637-a5f73bf18ac4.png">

**Comment by yoyurec** [comment]
how about this styling?
![image](https://user-images.githubusercontent.com/137919/189372285-b3816ce0-2fc1-40b3-8582-1865f05944d0.png)

**Comment by memeplex** [comment]
Looks nice to me!

**Comment by yoyurec** [comment]
will be in next release soon

**Comment by memeplex** [comment]
Great, thank you very much!

**Comment by yoyurec** [comment]
check latest release

**Comment by memeplex** [comment]
Looks great!
