### ISSUE TITLE
Only the first half of the content can be exported

### ISSUE THREAD

**Issue by lion-no-back** [yoyurec/logseq-solarized-extended-theme#49]
Using the logseq-solarized-extended-theme theme, when exporting through the logseq-plugin-doc plugin, only the first half of the content can be exported, that is, the viewport is visible, communicate with the developers of the logseq-plugin-doc plugin, and think that it may be the logseq lazy loading mechanism caused, but the problem is that other theme exports do not have this problem, only
The logseq-solarized-extended-theme theme has this problem. I like this theme very much and don’t want to give it up. At present, the export problem is not satisfactory.I hope it can be optimized and solved.

![20220908_113825_690_copy](https://user-images.githubusercontent.com/100990301/189028780-d916c713-5bff-4cf5-89c8-a9f81d6939dd.png)

**Comment by yoyurec** [comment]
> only the first half of the content can be exported

what do you mean? page cutted at bottom or no right sidebar?

**Comment by lion-no-back** [comment]
For example, for an article, only the header is exported. Normally, it should be all exported. There is a slider on the right sidebar that can be slid down, but now I can't do this after using this theme. I can only export the header and the rest of the content can't export

**Comment by lion-no-back** [comment]
It can be simply understood that the export content is incomplete after using this plugin

**Comment by yoyurec** [comment]
can you attach exported files to test?

> It can be simply understood that the export content is incomplete after using this plugin
for me works ok...

**Comment by yoyurec** [comment]
> can you attach exported files to test?
> 
> > It can be simply understood that the export content is incomplete after using this plugin
> 
> for me works ok...

aha... on latest version of logseq-plugin-doc i see the issue. solution found, will be fixed in next theme version

**Comment by yoyurec** [comment]
check latest release

**Comment by lion-no-back** [comment]
Ok.The problem is solved.
