### ISSUE TITLE
Overlap between menubar buttons

### ISSUE THREAD

**Issue by AvijeetPrasad** [yoyurec/logseq-solarized-extended-theme#5]
**Info:**
- OS: macOS Monterey (12.3.1), Apple M1 Pro
- Logseq ver: 0.6.8
- Theme ver: 1.6.4
- [ ] Do I have the same issue on default theme? No

**Description:**

There is an overlap between the menubar buttons, and the button for accessing the left sidebar is not accessible. Please see the screenshot below.

**Screenshots**
![Screenshot 2022-05-14 at 06 32 22](https://user-images.githubusercontent.com/45669486/168410728-4619b52a-e46f-41e3-9bed-22bc466691a1.jpg)

**Comment by yoyurec** [comment]
Fixed! Check latest 1.6.6
