### ISSUE TITLE
Is there any approach to customize syntax highlight of code block?

### ISSUE THREAD

**Issue by mmssddss** [yoyurec/logseq-solarized-extended-theme#51]
**Idea**
the default syntax highlight of code block is not pretty as I expected
It will be great if the syntax highlight theme could be customized.
Is there any plan on this?

**Comment by yoyurec** [comment]
inline code or CodeMirror blocks?

**Comment by mmssddss** [comment]
codemirror blocks
I have noticed most of the logseq theme are using default syntax highlight

**Comment by yoyurec** [comment]
CodeMirror has own themes
https://discord.com/channels/725182569297215569/752845138148982877/990721939062530128

> quick heads-up for people who where using codemirror themes to style their code blocks: it seems Codemirror is now at version 6, and the link to the css themes should now be updated to add an extra /5 : 
> so in custom.css, instead of 
> @import "https://codemirror.net/theme/%themename%.css"; it should now be 
> @import "https://codemirror.net/5/theme/%themename%.css"; 
> (for moxer.css this would be @import "https://codemirror.net/5/theme/moxer.css";
> 
> related link about how to add extra options and themes  for code blocks: https://github.com/logseq/logseq/pull/3699
