### ISSUE TITLE
Nerd font, font awesome

### ISSUE THREAD

**Issue by itsamemarkus** [yoyurec/logseq-solarized-extended-theme#52]
**Idea**
I'd like to have the option to select a nerd font or font awesome as a font.

**Screenshots**
I think it would be cool to also have that applied for `icon::`
Reason is that you can make your page icons and favorites more specific than with default emojis.

Example:
![image](https://user-images.githubusercontent.com/34944988/190876293-5cf32ca4-a52b-46ba-9967-09700d441aa2.png)

**Attach files**
Link you provided on Discord:

https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/FiraCode#browser-support

Links to main sites:

https://www.nerdfonts.com/
https://fontawesome.com/

**Comment by yoyurec** [comment]
good idea... 
but most (my and others) themes using **sans** fonts, not monospace for classic (non-code) text (((

would be cool to find FiraSans nerd, or patch it with icons by myself....

**Comment by yoyurec** [comment]
test latest release
usage - https://github.com/yoyurec/logseq-solarized-extended-theme#-custom-page-icons
