### ISSUE TITLE
The forward/backward button and searching part of part displays incorrectly when opening PDF

### ISSUE THREAD

**Issue by artemith** [yoyurec/logseq-solarized-extended-theme#53]
**Info:**
- OS: Windows 10 21H2
- Logseq ver: 0.8.7
- Theme ver: 2.4.0
- [ √ ] ⚠ Do i have issue on SolExt theme with DISABLED my `custom.css`?
- [ × ] ⚠ Do i have the same on default theme?

**Description:**
A clear and concise description of what the bug is......
when opening a PDF, the forward/backward button and searching part is squeezed to right.

**To Reproduce:**
 ...

**Expected behavior:**
 ...

**Screenshots**
![image](https://user-images.githubusercontent.com/14881525/190882341-a15d38bd-2e65-4106-958e-3f6943021d5e.png)

**Attach files**
Add (via drag-n-drop) .zip with `.md` files (if it needs) to help with bugfixind

**Comment by yoyurec** [comment]
fixed! check latest update

**Comment by artemith** [comment]
Thank you!
