### ISSUE TITLE
Option to disable/enable calendar icon for journal pages

### ISSUE THREAD

**Issue by senntore** [yoyurec/logseq-solarized-extended-theme#54]
**Idea**

The calendar icon for journal pages has fixed date on them, that feel very wrong & confusing to me.
I can see few ways of solving this:
- Make the icon dynamic to suit the current date or journal page they belong to.
- Remove the date/month from the icon & change it to something more vague, but still identify as journal page.
- Provide option to disable or enable the icons for journal page, like you've option to disable the favicon for external links.

Thanks for your amazing work in the extension, I especially love the last few updates.

**Comment by yoyurec** [comment]
dynamic SVG can be a pain and too much work for so small thing: different langs, different date locale settings to parse... i think will just change icon to calendar without day.
on windows current emoji better than on mac )
![image](https://user-images.githubusercontent.com/137919/191297903-162a0209-bca5-41ad-906b-e14cf816ac1b.png)

**Comment by yoyurec** [comment]
something like this 
![image](https://user-images.githubusercontent.com/137919/191405540-b49319a1-d7de-417b-a472-3a1b4d27277a.png)

**Comment by senntore** [comment]
This looks neat! Does it also looks like that on linux?

**Comment by yoyurec** [comment]
yes, it's svg, not emoji (which has tens of variation, depending on provider)

**Comment by yoyurec** [comment]
check latest release 2.5.x
