### ISSUE TITLE
Feature request: Add the GTD matrix

### ISSUE THREAD

**Issue by mzwlevi** [yoyurec/logseq-solarized-extended-theme#55]
**Idea**
Add the GTD matrix 

**Screenshots**
![Screen Shot 2022-09-22 at 03 14 01](https://user-images.githubusercontent.com/78029539/191590865-27f9b129-1d6a-4984-b8ac-fc690fe282a5.png)

**Comment by yoyurec** [comment]
isn't there already some plugin for this? or CSS snippet?

**Comment by mzwlevi** [comment]
> isn't there already some plugin for this? or CSS snippet?

I found the logwidgets in marklet, thank you!
