### ISSUE TITLE
Kanban issue: Cannot see the content of backlinks when using [[]] to search.

### ISSUE THREAD

**Issue by mzwlevi** [yoyurec/logseq-solarized-extended-theme#6]
**Info:**
- OS: MacOS
- Logseq ver: 0.6.8
- Theme ver: 1.6.6
- [x] Do i have the same on default theme? 

**Description:**
Kanban issue: Cannot see the content of backlinks when using [[]]&(()) to search.

**Screenshots**
<img width="876" alt="Screen Shot 2022-05-14 at 15 01 26" src="https://user-images.githubusercontent.com/78029539/168414932-9eb1d94d-6105-4844-b949-600875599aab.png">

**Comment by mzwlevi** [comment]
<img width="912" alt="Screen Shot 2022-05-14 at 15 06 39" src="https://user-images.githubusercontent.com/78029539/168414980-46a86172-4293-493d-b1c7-bc9dfca955cb.png">
same issue on default theme

**Comment by mzwlevi** [comment]
![Screen Shot 2022-05-14 at 15 11 19](https://user-images.githubusercontent.com/78029539/168415138-2aa4dff6-7e7e-4738-a1b3-ca151272a397.png)
This is the present in roamresearch

**Comment by yoyurec** [comment]
can you post markdown as code here?

**Comment by yoyurec** [comment]
> same issue on default theme

i think you can also create bug issue in LS repo - https://github.com/logseq/logseq/issues

**Comment by yoyurec** [comment]
> same issue on default theme

how? default theme have no columns support )))

**Comment by mzwlevi** [comment]
> > same issue on default theme
> 
> how? default theme have no columns support )))

I copy the #kanban css into the default theme

**Comment by mzwlevi** [comment]
Could you try this issue in solarized-extended-theme, maybe this can be reproduced, cannot use [[]] with search in #kanban. the search will be hidden.

**Comment by yoyurec** [comment]
> I copy the #kanban css into the default theme

that means you USE my theme some kind ))
by quesion "do it reproduced in default" i want to exclude my theme as root cause

**Comment by yoyurec** [comment]
i check and this issue in my theme. already fixed. soon will be new release

**Comment by yoyurec** [comment]
fixed in 1.6.7
